name: TitanGames
version: ${project.version}
main: com.stardevmc.titangames.TitanGames
api-version: 1.13
depend: [FireLib]
authors: [Firestar311]
description: A Survival Games plugin
commands:
    titangames:
        aliases: [tg]
